# This file was generated by GoReleaser. DO NOT EDIT.
cask "same" do
  name "same"
  desc "Modern build tool for monorepos"
  homepage "https://github.com/traiproject/same"
  version "0.1.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "same"
  bash_completion "completions/same.bash"
  zsh_completion "completions/same.zsh"
  fish_completion "completions/_same.fish"

  on_macos do
    on_intel do
      url "https://github.com/traiproject/same/releases/download/v#{version}/same_#{version}_macOS_x86_64.tar.gz"
      sha256 "c7373ccdd7b6f929709a72c4d81bc60b0078d327485b7546d4c580aeacac5003"
    end
    on_arm do
      url "https://github.com/traiproject/same/releases/download/v#{version}/same_#{version}_macOS_arm64.tar.gz"
      sha256 "65476ba3bfb78ab6faddcbdf4f7023cb148343ec94f7e6e8d0b9f305ee0596ae"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/traiproject/same/releases/download/v#{version}/same_#{version}_linux_x86_64.tar.gz"
      sha256 "9527f95d286c3dd706dbb0c8c3d14c9ddef28cbf4d2be837d793a299c3db06a1"
    end
    on_arm do
      url "https://github.com/traiproject/same/releases/download/v#{version}/same_#{version}_linux_arm64.tar.gz"
      sha256 "6940a11062533d9c8a7c634402665e7bf815bdbcbf834aa0dfad92559fe55587"
    end
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/same"] if OS.mac?
  end

  # No zap stanza required
end
