# This file was generated by GoReleaser. DO NOT EDIT.
cask "same" do
  # rubocop:disable Cask/StanzaOrder, Cask/StanzaGrouping

  name "same"
  desc "Modern build tool for monorepos"
  homepage "https://github.com/traiproject/same"
  version "0.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "same"
  bash_completion "completions/same.bash"
  zsh_completion "completions/same.zsh"
  fish_completion "completions/_same.fish"

  on_macos do
    on_intel do
      url "https://github.com/traiproject/same/releases/download/v#{version}/same_#{version}_macOS_x86_64.tar.gz"
      sha256 "8f3cfc70551ed2dffece3da1c98e6a665318118251a4ee43d2957411d70b7ee9"
    end
    on_arm do
      url "https://github.com/traiproject/same/releases/download/v#{version}/same_#{version}_macOS_arm64.tar.gz"
      sha256 "97bde8efd5a129e5ae484882911f0a69cdb9080cdc64c919f76163f7c9b0f660"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/traiproject/same/releases/download/v#{version}/same_#{version}_linux_x86_64.tar.gz"
      sha256 "9b6ffbd2e63022ab14ad22956eed6ad9bddf86073ab4fc544d3c9f1ce9efda07"
    end
    on_arm do
      url "https://github.com/traiproject/same/releases/download/v#{version}/same_#{version}_linux_arm64.tar.gz"
      sha256 "75bee9d38cd9bd6fe6a0cded3cdad05bfa8813b1800fdf2fe3d697e8951f46da"
    end
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/same"] if OS.mac?
  end

  # No zap stanza required
end
