# This file was generated by GoReleaser. DO NOT EDIT.
cask "same" do
  name "same"
  desc "Modern build tool for monorepos"
  homepage "https://github.com/traiproject/same"
  version "0.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "same"
  bash_completion "completions/same.bash"
  zsh_completion "completions/same.zsh"
  fish_completion "completions/_same.fish"

  on_macos do
    on_intel do
      url "https://github.com/traiproject/same/releases/download/v#{version}/same_#{version}_macOS_x86_64.tar.gz"
      sha256 "988b49d896e400a1e1a8718efeb585bfe39234f4621fba3004b9c1e93ceb39d4"
    end
    on_arm do
      url "https://github.com/traiproject/same/releases/download/v#{version}/same_#{version}_macOS_arm64.tar.gz"
      sha256 "1461ff703666742a02aec320bc3cddd8d0d3d083c2c334c2559e02124162b15d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/traiproject/same/releases/download/v#{version}/same_#{version}_linux_x86_64.tar.gz"
      sha256 "9853b2a0bbf531d9f11a6340d788550c6525ffc8884b0c6edeee12470b04eb7b"
    end
    on_arm do
      url "https://github.com/traiproject/same/releases/download/v#{version}/same_#{version}_linux_arm64.tar.gz"
      sha256 "09a081877b45f53b68c3344ef92f60416b7ec292859e038120bb971c2e5818ab"
    end
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/same"] if OS.mac?
  end

  # No zap stanza required
end
